version: "2.3"

x-logging: &default-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "5"

services:

  qgisserver:
    restart: always
    image: napkingis/qgis-server:3.4
    volumes:
      - publish:/publish/
    expose:
      - 90

  django:
    restart: always
    image: napkingis/django
    volumes:
      - db-data:/var/www/napkingis/data/
      - publish:/publish/
      - assets:/assets/
      - media:/var/www/napkingis/media/
      - ./django/settings.custom/:/var/www/napkingis/djproject/custom/:ro
    environment:
      - GUNICORN_WORKERS=2
      - GUNICORN_ERRORLOG=-
      - GUNICORN_ACCESSLOG=-
      - DJANGO_STATIC_URL=/django/static/
      - DJANGO_STATIC_ROOT=/assets/django/static/
      - DJANGO_MEDIA_URL=/media/
      - DJANGO_MEDIA_ROOT=/var/www/napkingis/media/
      - DJANGO_LANGUAGE_CODE=en-us
      - DJANGO_SECRET_KEY=${SECRET_KEY}
      - GISQUICK_SQLITE_DB=/var/www/napkingis/data/gisquick.sqlite3
    env_file:
      - django.env
    expose:
      - 8000
    logging: *default-logging

  go:
    restart: always
    image: napkingis/settings
    volumes:
      - publish:/publish/
      - media:/var/www/media/
    environment:
      - PROJECTS_ROOT=/publish
      - MAP_CACHE_ROOT=/var/www/media/cache
      - SERVER_URL=http://django:8000
      - MAPSERVER_URL=http://qgisserver:90/cgi-bin/qgis_mapserv.fcgi
      - MAX_FILE_UPLOAD=250M
      - MAX_PROJECT_SIZE=250M
    expose:
      - 8001
    logging: *default-logging

  nginx:
    restart: always
    image: nginx
    volumes:
      - assets:/var/www/html/
      - media:/var/www/media/
      - ./nginx/conf.local/:/etc/nginx/conf.d/
      - ./nginx/error/:/var/www/error/
    ports:
      - 4000:80
    logging: *default-logging

  web-map:
    image: napkingis/web-map
    volumes:
      - assets:/assets/
    command: "copy-assets /var/www /assets/map"

  web-user:
    image: napkingis/web-user
    volumes:
      - assets:/assets/
    command: "copy-assets /var/www /assets/user"

  web-accounts:
    image: napkingis/web-accounts
    volumes:
      - assets:/assets/
    command: "copy-assets /var/www /assets/accounts"

volumes:
  publish:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/publish/
      o: bind
  db-data:
  assets:
  media:
